project:
  type: "website"
  title: "Computational Social Science 2025/26"
  output-dir: docs
  render:
    - "index.qmd"
    - "2025/*.qmd"
    - "2025/weeks/week01/*.qmd"
    - "2025/weeks/week02/*.qmd"
    - "2025/weeks/week03/*.qmd"
    - "2025/weeks/week04/*.qmd"
    - "2025/weeks/week05/*.qmd"
    - "2025/weeks/week06/*.qmd"
    - "2025/weeks/week07/*.qmd"
    - "2025/weeks/week08/*.qmd"
    - "2025/weeks/week09/*.qmd"
    - "2025/workshop/rworkshop/*.qmd"
    - "2025/syllabus/rsyllabus/*.qmd"

website:
  title: "Computational Social Science 2025/26"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card: 
    creator: "@socioburak"
    site: "\\@socioburak"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: 2025/index.qmd
        text: "ğŸ  Home"
      - section: "ğŸ““ Syllabus"
        contents:
        - href: 2025/syllabus/rsyllabus/syllabus.qmd
          text: "ğŸ““ Syllabus" 
          contents:
      - section: "ğŸ“Ÿ R Workshop"
        contents:
         - href: 2025/workshop/rworkshop/page.qmd
           text: "ğŸ“Ÿ R Workshop Slides"
           contents:
      #      - href: 2025/workshop/rworkshop/page.qmd
      #        text: "ğŸ“Ÿ R Workshop"
      #     - href: 2025/assignments/assignment02.qmd
      #       text: "ğŸ“ Assignment 02"
      - section: "ğŸ—“ï¸ Weeks"
        contents:
         - href: 2025/weeks/week01/page.qmd
           text: Week 01
           contents:
             - href: 2025/weeks/week01/page.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
         - href: 2025/weeks/week02/page2.qmd
           text: Week 02
           contents:
             - href: 2025/weeks/week02/page2.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material 
         - href: 2025/weeks/week03/page3.qmd
           text: Week 03
           contents:
             - href: 2025/weeks/week03/page3.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material  
         - href: 2025/weeks/week04/page4.qmd
           text: Week 04
           contents:
             - href: 2025/weeks/week04/page4.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
         - href: 2025/weeks/week05/page5.qmd
           text: Week 05
           contents:
             - href: 2025/weeks/week05/page5.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
         - href: 2025/weeks/week06/page6.qmd
           text: Week 06
           contents:
             - href: 2025/weeks/week06/page6.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material 
         - href: 2025/weeks/week07/page7.qmd
           text: Week 07
           contents:
             - href: 2025/weeks/week07/page7.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
         - href: 2025/weeks/week08/page8.qmd
           text: Week 08
           contents:
             - href: 2025/weeks/week08/page8.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material
         - href: 2025/weeks/week09/page9.qmd
           text: Week 09
           contents:
             - href: 2025/weeks/week09/page9.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Material       
            #  - href: 2025/weeks/week01/lab.qmd
            #    text: ğŸ’» Lab Roadmap
            #  - href: 2025/weeks/week01/appendix.qmd
            #    text: ğŸ”– Appendix
      #- section: "ğŸ“Ÿ R Workshop"
       # contents:
        # - href: 2025/workshop/rworkshop/page.qmd
         #  text: ğŸ“Ÿ R Workshop
          # contents:
           #  - href: 2025/workshop/rworkshop/page.qmd
             #  text: ğŸ‘¨â€ğŸ« Workshop Material
  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2025, Burak Sonmez" 



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr [Burak Sonmez](#)
    author-meta: Dr Burak Sonmez
    date-format: "DD MMMM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:brksnmz\.github\.io\/|localhost)

    theme:
      light: 
        - journal
        - css/custom.scss # I use this just to change the default colour
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true

margin-header: |
 ![](/figures/logos/MY_INSTITUTION.jpeg)

